config/routes.rb
Rails.application.routes.draw do
  #get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <nav class="navbar-inverse">
      <%= link_to 'One Page', root_path %>
      <%= link_to 'Two Page', pages_two_path %>
      <%= link_to 'Three Page', pages_three_path %>
    </nav>

    

    <%= yield %>
  </body>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/pages/one.html.erb
<h1>Sergio Eduardo Herrera Carmona </h1>
<p>first app on rails</p>

app/views/pages/three.html.erb
<h2>lorem ipsum </h2>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad voluptas ullam pariatur nam aperiam voluptates totam ex hic error beatae perspiciatis nisi quae inventore aliquam et rerum consequuntur, in exercitationem!</p>

app/views/pages/two.html.erb
<h1>Pagina two ,insertando imagen</h1>
<p>actualmente estoy en rails 6 , el comando para obtener las rutas se cambia de rake routes por rails routes</p>
<%= image_tag 'rake_routes.png', class:'print console', id: 'main-bg',alt:'print comand rails routes' %>